# Generated by Django 6.1.1 on 2026-09-24 14:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_profile_picture_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customuser',
            name='numero_cef',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='N° Inscription (CEF)'),
        ),
    ]
