# Generated by Django 6.1.1 on 2026-09-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_last_activity_customuser_numero_cef'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_maintenance', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
