# Generated by Django 6.1.1 on 2026-09-25 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_cahiertexte'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CahierTexte',
        ),
    ]
