# Generated by Django 6.1.1 on 2026-09-24 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_absence_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='student',
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={},
        ),
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absences', models.IntegerField(default=0)),
                ('note_python', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('note_linux', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('note_reseau', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Absence',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
