# Generated by Django 6.1.1 on 2026-09-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_cahiertexte_supportticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetStagiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('students', models.CharField(max_length=255)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
